# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.245.2/containers/debian/.devcontainer/base.Dockerfile
FROM mcr.microsoft.com/devcontainers/go:0-1-bullseye

# Change default shell to bash
RUN ln -fs /bin/bash /bin/sh
